FROM python:3.6

RUN apt-get update && apt-get install -y git curl

WORKDIR /app

RUN git clone https://github.com/zvrvdmtr/rehab.git .

RUN pip install -r requirements.txt

RUN python3 manage.py migrate