version: "3.7"

services:
    db:
        image: postgres:12
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    api:
        build:
            context: .
            dockerfile: Dockerfile.web
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        depends_on:
            - db