version: "3.7"

services:
        
    app:
        container_name: rehab_app
        build: 
            context: .
            dockerfile: Dockerfile.web
        command: make docker-run-app
        ports:
            - 8000:8000