# Generated by Django 3.0.8 on 2020-07-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Prcatice title')),
                ('injury_type', models.CharField(max_length=128, verbose_name='Injury type')),
                ('reps', models.PositiveIntegerField(verbose_name='Reps number')),
                ('loops', models.PositiveIntegerField(verbose_name='Loops number')),
                ('description', models.TextField(max_length=256, verbose_name='Practice description')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
            },
        ),
    ]
